### PR TITLE
RATIS-1841. Fixed bug where cluster restart failed to transfer snapshot.

### PR DESCRIPTION
**Pull request by OneSizeFitsQuorum**
see [RATIS-1841](https://issues.apache.org/jira/browse/RATIS-1841)

### CODE REVIEW

**Comment by OneSizeFitsQuorum** [comment]
@szetszwo PTAL

**Review by SzyWilliam — APPROVED** [review]
+1 LGTM

**Comment by szetszwo** [comment]
@OneSizeFitsQuorum , RATIS-1838 is already resolved.  Please file a new JIRA for this.

**Comment by OneSizeFitsQuorum** [comment]
> @OneSizeFitsQuorum , [RATIS-1838](https://issues.apache.org/jira/browse/RATIS-1838) is already resolved. Please file a new JIRA for this.

Thank you for reminding me. I have created an issue~

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by szetszwo** [comment]
@OneSizeFitsQuorum , thanks a lot for working on this!

@SzyWilliam , thanks for reviewing this!

**Pull request merged**
