### PR TITLE
RATIS-1778. Fix NPE in readIndexHeartbeats

### PR DESCRIPTION
**Pull request by codings-dan**
See https://issues.apache.org/jira/browse/RATIS-1778

This is a retry of https://github.com/apache/ratis/pull/817

### CODE REVIEW

**Review by kaijchen — APPROVED** [review]
LGTM

**Comment by codings-dan** [comment]
@szetszwo Could you help take a look the pull request? Thanks!

**Review by SzyWilliam — APPROVED** [review]
@codings-dan Thanks for working on this! The change looks good to me.

**Comment by codings-dan** [comment]
@kaijchen @SzyWilliam Thanks for helping review the pull request!

**Comment by szetszwo** [comment]
+1 the change looks good.

Sorry that I missed this earlier.

**Pull request merged**
