### PR TITLE
RATIS-1733. Typo: fix misleading params names in `RaftServerConfigKeys`

### PR DESCRIPTION
**Pull request by SzyWilliam**
See https://issues.apache.org/jira/browse/RATIS-1733

### CODE REVIEW

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by szetszwo** [comment]
@SzyWilliam , TestReadOnlyRequestWithGrpc just have failed in the last build, although it is not related to this change; see https://github.com/apache/ratis/actions/runs/3346622398/jobs/5564386148#step:5:604 .  Could you take a look?

**Comment by SzyWilliam** [comment]
@szetszwo The method `testFollowerLinearizableReadRetryWhenLeaderDown` seems always fail. The error stack is complicated and I found `Caused by: java.io.NotSerializableException: org.apache.ratis.protocol.RaftGroupMemberId`. I suspect that the LeaderNotException returned here [1] contains the RaftGroupMemberId that cannot be serialized. Should we implement 'Serializable` for `RaftGroupMemberId`?
[1] https://github.com/apache/ratis/blob/903cd17c0b0615bfec80afeac796354b9d99a1fd/ratis-server/src/main/java/org/apache/ratis/server/impl/LeaderStateImpl.java#L1094

**Comment by szetszwo** [comment]
@SzyWilliam , thanks for 

```java
```

**Comment by SzyWilliam** [comment]
@szetszwo Thanks for providing the patch! The good news is that this `NotSerializableException` disappears this time. The bad news is there's another error occurred. I'll take a look at it.

**Review by szetszwo — APPROVED** [review]
+1 the new change looks good.

**Pull request merged**
