### PR TITLE
RATIS-1934. Support Zero-Copy in GrpcServerProtocolService

### PR DESCRIPTION
**Pull request by duongkame**
## What changes were proposed in this pull request?

Support Zero-Copy in GrpcServerProtocolService.appendEntries

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1934

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by duongkame** [comment]
A test is failing because log entries for configuration has it zero-copy buffer released too early ppening on #1021 for a fix.

**Comment by duongkame** [comment]
@szetszwo can you have a look?

**Comment by szetszwo** [comment]
@duongkame , The peer ids are corrupted; see https://github.com/apache/ratis/actions/runs/7573336528/job/20625244115?pr=1014#step:6:739

**Comment by duongkame** [comment]
> #1021

Yes, pening 

> @duongkame , The peer ids are corrupted; see https://github.com/apache/ratis/actions/runs/7573336528/job/20625244115?pr=1014#step:6:739

Yeah, pending fix by https://github.com/apache/ratis/pull/1021. @szetszwo

**Comment by duongkame** [comment]
RATIS-2009 is done. Merge from master fixed the problem with peer ids corrupted. @szetszwo

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Pull request merged**
