### PR TITLE
RATIS-2080. Reuse LeaderElection executor.

### PR DESCRIPTION
**Pull request by szetszwo**
See  RATIS-2080

### CODE REVIEW

**Comment by guohao-rosicky** [comment]
+1 LGTM. Thanks @szetszwo work on this.

**Review by guohao-rosicky — APPROVED** [review]

**Comment by szetszwo** [comment]
@guohao-rosicky , thanks a lots for reviewing this!

**Comment by guohao-rosicky** [comment]
Hi @szetszwo, Did you find anything wrong and why revert this commit?

**Comment by szetszwo** [comment]
@guohao-rosicky , the leader election tests seem to fail more often.  So, I have reverted this.

**Comment by szetszwo** [comment]
@guohao-rosicky , BTW, RATIS-2076 has fixed `LeaderElection.shutdown()`. It seems that we no longer need this change.

**Comment by guohao-rosicky** [comment]
Thanks @szetszwo. I see [RATIS-2076](https://issues.apache.org/jira/browse/RATIS-2076).

**Pull request merged**
