### PR TITLE
RATIS-1512. Remove hadoop related components from ratis.git.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1512

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
* Should `ratis-proto/src/main/proto/Hadoop.proto` also move?
* There is some Hadoop-specific logic in `ratis-resource-bundle/src/main/resources/META-INF/LICENSE.vm`.
* `BUILDING.md` mentions the separate (nonexistent) repo `ratis-thirdparty-hadoop` and that `org.apache.hadoop.ipc.protobuf` should be shaded.  Is this still planned?

**Comment by szetszwo** [comment]
@adoroszlai , thanks a lot for your comments.

> Should ratis-proto/src/main/proto/Hadoop.proto also move?

Yes.  

> There is some Hadoop-specific logic in ratis-resource-bundle/src/main/resources/META-INF/LICENSE.vm.

Good catch.  We should remove the  Hadoop-specific logic.

> BUILDING.md mentions the separate (nonexistent) repo ratis-thirdparty-hadoop and that org.apache.hadoop.ipc.protobuf should be shaded. Is this still planned?

The ratis-thirdparty-hadoop module was renamed to ratis-thirdparty-misc some time ago.  Let me update the doc.

**Review by adoroszlai — COMMENTED** [review]
Thanks @szetszwo for updating the patch.

While the cleanup in `LICENSE.vm` is nice, I wonder if we should remove content related to JQuery, JRuby and other components in a separate PR.  Are these related to Hadoop or simply leftover from older dependency changes?  They also need tweaks in `NOTICE.vm`.

**Comment by szetszwo** [comment]
@adoroszlai , LICENSE.vm will first detect the existence of a component.  It generates the license only if the component exists.  Since it doesn't hurt, how about we keep LICENSE.vm unchanged?

Just have compared the original LICENSE.vm with the modified LICENSE.vm (with Hadoop and other components removed).  The generated LICENSE files are the same for both cases.

Updated the code with LICENSE.vm reverted.

**Review by adoroszlai — APPROVED** [review]

**Pull request merged**
