### PR TITLE
RATIS-1328. Avoid parse proto for each packet

### PR DESCRIPTION
**Pull request by runzhiwang**
## What changes were proposed in this pull request?

Avoid parse proto for each packet

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1328

## How was this patch tested?

no need new ut

### CODE REVIEW

**Review by szetszwo — APPROVED** [review]
+1 the patch looks good.

**Comment by szetszwo** [comment]
@runzhiwang , how about we include this in the 2.0.0 release since this is an incompatible change?

**Comment by runzhiwang** [comment]
@szetszwo Okay, let me release rc3.

**Comment by szetszwo** [comment]
Thanks a lot.

**Pull request merged**
