### PR TITLE
RATIS-1313. Use matrix build for unit tests to reduce CI time

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Execute tests in 3 splits to speed up CI feedback a bit.  Split are defined via Maven profiles.  This reduces time required for _unit_ check to about 10 minutes.

https://issues.apache.org/jira/browse/RATIS-1313

## How was this patch tested?

Compared list of tests from Maven output to a previous, single run.  Verified that no tests are missed, and each of them is executed only once.

https://github.com/adoroszlai/incubator-ratis/actions/runs/551983793

### CODE REVIEW

**Comment by adoroszlai** [comment]
@szetszwo @runzhiwang can someone please review?

**Comment by cnauroth** [comment]
+1 (non-binding)

That's a really nice improvement.  The changes look good.  I spot checked CI output for any missing or duplicated test runs, but it all looked good to me.  Thanks, @adoroszlai !

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by adoroszlai** [comment]
Thanks @cnauroth, @runzhiwang, @szetszwo for the review.

**Comment by szetszwo** [comment]
Hey @adoroszlai ,
image

Is it the case that if the grpc tests have failed, the server and the misc tests will be cancelled?  It seems better to always run all the tests since the overall running time is short.  This is the reason that we moved the tests to the ratis-test module; see https://issues.apache.org/jira/browse/RATIS-399

**Comment by adoroszlai** [comment]
> Is it the case that if the grpc tests have failed, the server and the misc tests will be cancelled?

Correct.  I will post a follow-up change to always run all tests for `push` and `schedule` builds, but keep this fail-fast behavior for PRs.

**Comment by szetszwo** [comment]
That's great.  Thanks for the fast response!

**Pull request merged**
