### PR TITLE
RATIS-2182. Fix some Objects.requireNonNull messages

### PR DESCRIPTION
**Pull request by jianghuazhu**
## What changes were proposed in this pull request?
In Ratis, some of the messaging for Objects.requireNonNull() is not clear enough. The purpose of this PR is to try to fix that.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/RATIS-2182

## How was this patch tested?
ci: 
https://github.com/jianghuazhu/ratis/actions/runs/11590363184

### CODE REVIEW

**Comment by jianghuazhu** [comment]
@szetszwo , can you help review this PR?
Thanks.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by szetszwo** [comment]
@jianghuazhu , thanks a lot for working on this!  

`TestRaftWithGrpc` failed in the previous run.  Let's rerun it.

BTW, please see if you have time to fix the remaining zero-copy bugs.  We may enable advanced tracing as below and rerun the test until it fails.  Then, check the retain-release trace to see why an object is released properly.

```diff
+++ b/ratis-grpc/src/test/java/org/apache/ratis/grpc/MiniRaftClusterWithGrpc.java
@@ -52,7 +52,7 @@ public class MiniRaftClusterWithGrpc extends MiniRaftCluster.RpcBase {
 
   static {
     // TODO move it to MiniRaftCluster for detecting non-gRPC cases
-    ReferenceCountedLeakDetector.enable(false);
+    ReferenceCountedLeakDetector.enable(true);
   }
```

**Comment by jianghuazhu** [comment]
> @jianghuazhu , thanks a lot for working on this!
> 
> `TestRaftWithGrpc` failed in the previous run. Let's rerun it.
> 
> BTW, please see if you have time to fix the remaining zero-copy bugs. We may enable advanced tracing as below and rerun the test until it fails. Then, check the retain-release trace to see why an object is released properly.
> 
> ```diff
> +++ b/ratis-grpc/src/test/java/org/apache/ratis/grpc/MiniRaftClusterWithGrpc.java
> @@ -52,7 +52,7 @@ public class MiniRaftClusterWithGrpc extends MiniRaftCluster.RpcBase {
>  
>    static {
>      // TODO move it to MiniRaftCluster for detecting non-gRPC cases
> -    ReferenceCountedLeakDetector.enable(false);
> +    ReferenceCountedLeakDetector.enable(true);
>    }
> ```

Thanks @szetszwo  for the comment and review.
I will try to fix the `TestRaftWithGrpc` test failure and I will create a new jira later.

**Pull request merged**
