### PR TITLE
RATIS-2093. Decouple metadata and configuration entries from appendEntries buffer for stateMachineCache'

### PR DESCRIPTION
**Pull request by duongkame**
## What changes were proposed in this pull request?

See RATIS-2093.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-2093

### CODE REVIEW

**Comment by duongkame** [comment]
@szetszwo can you have a look?

**Review by szetszwo — COMMENTED** [review]
@duongkame , thanks for working on this!  Please see the comments inlined.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by duongkame** [comment]
Thanks for merging it @szetszwo . Sorry, I have to ask for another favor, can release a snapshot version after this commit?

**Comment by szetszwo** [comment]
@duongkame , deployed `3.1.0-640749b-SNAPSHOT`.

**Pull request merged**
