### PR TITLE
RATIS-2150. No need for manual assembly:single execution when mvn deploy

### PR DESCRIPTION
**Pull request by OneSizeFitsQuorum**
see [jira](https://issues.apache.org/jira/browse/RATIS-2150)

### CODE REVIEW

**Comment by OneSizeFitsQuorum** [comment]
@szetszwo PTAL

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Review by adoroszlai — COMMENTED** [review]
Thanks @OneSizeFitsQuorum for the patch, LGTM.

(Please continue using your fork for pushing development branches, instead of `apache/ratis`.)

**Comment by OneSizeFitsQuorum** [comment]
Thanks for  @reviewing! @szetszwo @adoroszlai 

| Please continue using your fork for pushing development branches, instead of apache/ratis

got it!

**Pull request merged**
