### PR TITLE
RATIS-2129. Low replication performance because of lock contention on RaftLog

### PR DESCRIPTION
**Pull request by szetszwo**
See RATIS-2129

(Temporally targeting to the `release-3.1.0` branch.  Will submit a pr for the master once this has passed all the tests.)

### CODE REVIEW

**Review by OneSizeFitsQuorum — COMMENTED** [review]
Awesome Design！

It seems that through this solution, we can convert the read lock of SegmentedRaftLog to the read lock of SegmentedRaftLogCache. This change means that the read-write conflicts caused by each write operation from the writing thread are now limited to when switching openSegment in SegmentedRaftLogCache. This approach appears to significantly reduce the overhead of synchronization locks.

Looking forward to future test result!

**Review by OneSizeFitsQuorum — APPROVED** [review]

**Comment by szetszwo** [comment]
@OneSizeFitsQuorum , thanks a lot for testing this!

**Comment by szetszwo** [comment]
Submitted https://github.com/apache/ratis/pull/1141 for the master branch.

**Comment by OneSizeFitsQuorum** [comment]
Hi, @szetszwo , we can close this PR because the release-3.1.x will not contain this PR and we can include this work in the future 3.2.0.

**Comment by szetszwo** [comment]
Sure, let's close this.

**Pull request closed without merging**
