### PR TITLE
RATIS-2074. Intermittent fork timeout in TestRaftWithNetty#testBasicAppendEntriesKillLeader.

### PR DESCRIPTION
**Pull request by szetszwo**
See RATIS-2074

### CODE REVIEW

**Comment by szetszwo** [comment]
@adoroszlai , could you test if this could fix the problem?

**Review by adoroszlai — APPROVED** [review]
Thanks @szetszwo for the patch.

Tried [100 runs](https://github.com/adoroszlai/ratis/actions/runs/8979309196) with it:
- RATIS-2074 did not happen
- RATIS-2076 happened in 6 runs (about the same rate as previously)

`Failed to close channel localhost:... in 10s` appears in 2 runs:
- split 7 iteration 5
- split 9 iteration 1

It may have appeared in successful runs, too, but those logs are not kept.

`testBasicAppendEntriesKillLeader` is successful even if channel cannot be closed.

So the patch fixes the fork timeout.

**Comment by szetszwo** [comment]
> `Failed to close channel localhost:... in 10s` appears in 2 runs:

Both cases seem okay
- split 7 iteration 5: Interrupted 
- split 9 iteration 1: Connection refused: localhost/127.0.0.1:15052 (network problem?)

**Comment by szetszwo** [comment]
> [RATIS-2076](https://issues.apache.org/jira/browse/RATIS-2076) happened in 6 runs (about the same rate as previously)

There were 300 threads running.  I suspect the failures was due to slowness.  Let's try increasing the timeout.

**Comment by adoroszlai** [comment]
> Let's try increasing the timeout.

Only 1/100 runs failed with 63490ea8:
https://github.com/adoroszlai/ratis/actions/runs/8989894896/job/24693966187#step:6:7592

**Comment by szetszwo** [comment]
@adoroszlai , thanks for testing and reviewing this!  Let's merge this PR first.  We can continue fixing the remaining problem on RATIS-2076.

**Pull request merged**
