### PR TITLE
RATIS-1751. Race condition between LeaderStateImpl & ServerState.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1751

### CODE REVIEW

**Review by SzyWilliam — APPROVED** [review]
Thanks for working on this!

**Review by codings-dan — APPROVED** [review]
@szetszwo Thanks for working on this! the change looks good, +1

**Comment by szetszwo** [comment]
@codings-dan , thanks a lot for reviewing and merging this!

**Comment by codings-dan** [comment]
@szetszwo My network cannot access the jira page recently for unkonwn reason. Could you help resolve this jira, thanks!

**Comment by szetszwo** [comment]
@codings-dan , just have resolved it.

**Pull request merged**
