### PR TITLE
RATIS-1886. AppendLog sleep fixed time cause significant drop in write throughput.

### PR DESCRIPTION
**Pull request by szetszwo**
See RATIS-1886

### CODE REVIEW

**Comment by szetszwo** [comment]
Found an unrelated NPE in the previous build:
```java
Caused by: java.lang.NullPointerException: leaderState == null
	at org.apache.ratis.server.impl.RoleInfo.shutdownLeaderState(RoleInfo.java:89)
	at org.apache.ratis.server.impl.RaftServerImpl.changeToFollower(RaftServerImpl.java:584)
	at org.apache.ratis.server.impl.RaftServerImpl.changeToFollowerAndPersistMetadata(RaftServerImpl.java:601)
	at org.apache.ratis.server.impl.LeaderStateImpl.stepDown(LeaderStateImpl.java:676)
	at org.apache.ratis.server.impl.LeaderStateImpl.checkLeadership(LeaderStateImpl.java:1080)
	at org.apache.ratis.server.impl.LeaderStateImpl$EventProcessor.run(LeaderStateImpl.java:738)
```
Will fix here since it is just a one line fix.

**Review by SzyWilliam — APPROVED** [review]
+1 the changes look good to me. Thanks @szetszwo a lot for the fixing the throughput drop!

It seems that writes with small payloads (<10ms) are more sensitive to the AppendLog sleep time. With this patch and other recent improvements, I can't wait to see the throuput improvements in 3.0.0🥇

**Review by codings-dan — APPROVED** [review]
LGTM

**Comment by szetszwo** [comment]
@SzyWilliam , @codings-dan , thanks a lot for reviewing this!

**Pull request merged**
