### PR TITLE
RATIS-1710. Refactor metrics api and implementation to separated modules.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1710

### CODE REVIEW

**Review by codings-dan — APPROVED** [review]
@szetszwo Thanks for working on this! The change looks good to me, +1 
BTW, should we just remove the `ratis-metrics` module directly?

**Comment by codings-dan** [comment]
> @codings-dan , thanks a lot for reviewing this!
> 
> > BTW, should we just remove the ratis-metrics module directly?
> 
> Do you mean we should not rename `ratis-metrics` to `ratis-metrics-api` and keep using the name `ratis-metrics`? I thought about it -- since the API has changed, it probably will have more confusion if we keep using `ratis-metrics`. The applications has to update the code anyway. Using also the module name is not a big deal.

Change the name is fine. I mean, since the `ratis-metrics` module is empty now, shouldn't we just remove it.

**Comment by szetszwo** [comment]
> ... since the ratis-metrics module is empty now, shouldn't we just remove it.

When a directory is empty, git will automatically remove it.  For example,   the ratis-metrics module is not in https://github.com/apache/ratis anymore.  For the local copies, we may need to remove it manually since there probably is a `target` directory or some other Ide files.

**Comment by codings-dan** [comment]
> When a directory is empty, git will automatically remove it.

I didn't know that git can be automatically remove empty dir,  thank you for telling me! Now `ratis-metrics` is indeed not in [ratis](https://github.com/apache/ratis)

**Pull request merged**
