### PR TITLE
RATIS-1454. NettyServerStreamRpc get request resolving concurrency se…

### PR DESCRIPTION
**Pull request by guohao-rosicky**
## What changes were proposed in this pull request?

NettyServerStreamRpc get request resolving concurrency security

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1454

### CODE REVIEW

**Comment by guohao-rosicky** [comment]
netty doc: https://netty.io/4.1/api/io/netty/util/AttributeKey.html

**Comment by guohao-rosicky** [comment]
@szetszwo , can you help review this patch?

**Comment by szetszwo** [comment]
@guohao-rosicky , Could you describe the details of the problem in more details? Did you see any exceptions?

**Comment by guohao-rosicky** [comment]
@szetszwo , I didn't find any exceptions, but you can see from netty document can do the same thing with AttributeMap.
```
private Final RequestRef RequestRef = new RequestRef();
``` 
changed by another `ChannelPipeline`, the `exceptionCaught` method obtained an incorrect value.

**Comment by szetszwo** [comment]
> ... you can see from netty document  ...

Could you provide the link to the netty doc?

**Comment by guohao-rosicky** [comment]
> > ... you can see from netty document  ...
> 
> Could you provide the link to the netty doc?

doc: 

https://netty.io/4.1/api/io/netty/util/AttributeMap.html

https://netty.io/4.1/api/io/netty/util/AttributeKey.html

https://netty.io/4.1/api/io/netty/channel/ChannelHandlerContext.html#name--

**Comment by szetszwo** [comment]
@guohao-rosicky , thanks, I read these netty API docs earlier.  Some questions:
- Is there a problem you observed?  If yes, could you show the datails?
- The calls might have shared the same context.  We need to verify it.
- Somehow the attr method ( https://netty.io/4.1/api/io/netty/channel/ChannelHandlerContext.html#attr-io.netty.util.AttributeKey- ) is deprecated.  So, it is not clear what is the correct way to use it.

**Comment by guohao-rosicky** [comment]
> @guohao-rosicky , thanks, I read these netty API docs earlier. Some questions:
> 
> * Is there a problem you observed?  If yes, could you show the datails?
> * The calls might have shared the same context.  We need to verify it.
> * Somehow the attr method ( https://netty.io/4.1/api/io/netty/channel/ChannelHandlerContext.html#attr-io.netty.util.AttributeKey- ) is deprecated.  So, it is not clear what is the correct way to use it.

1. There is a potential problem, but it has not been discovered
2. I used the `ChannelHandlerContext.name ()` this is the only name each context
3. I use `ctx.channel().attr()` and will not deprecated this method

**Comment by guohao-rosicky** [comment]
I will test in my test environment for a period of time and then update the test progress

**Comment by szetszwo** [comment]
> There is a potential problem, ...

The current code does not seem to have a potential problem since we have assertions in the set(..) and reset(..) methods in RequestRef.

If there is no problem observed, let's don't spend our energy to change this.  We have many other works going on.

**Comment by guohao-rosicky** [comment]
```
      @Override
      public void exceptionCaught(ChannelHandlerContext ctx, Throwable throwable) {
        Optional.ofNullable(requestRef.getAndSetNull())
            .ifPresent(request -> requests.replyDataStreamException(throwable, request, ctx));
      }
```
@szetszwo 
`requestRef.getAndSetNull()`Before calling, it is modified by other channel pipelines, causing an error message to be sent to other clients

**Comment by szetszwo** [comment]
> ... causing an error message to be sent to other clients

It seems not possible since requestRef already has asserted that only one request is process at a time in set/reset methods.

**Comment by guohao-rosicky** [comment]
> 

But won't this variable be modified by other channels before calling exceptionCaught in this ChannelPipeline? Set /reset is only guaranteed to remain unchanged within the channelRead method in this ChannelPipeline.

**Comment by szetszwo** [comment]
@guohao-rosicky , only set/reset methods can change the ref.  Suppose ref is set to requestA.  Only reset(requestA) can clear it.  There are no ways (even in other methods)  to set it to another request before that.

**Pull request closed without merging**
