### PR TITLE
RATIS-1332. Always remove raft-meta.tmp to clean uncommitted changes

### PR DESCRIPTION
**Pull request by symious**
## What changes were proposed in this pull request?

Always remove raft-meta.tmp to clean uncommitted changes.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1332

## How was this patch tested?

unit tests.

### CODE REVIEW

**Comment by symious** [comment]
@elek Could you help to review this PR?

**Review by runzhiwang — APPROVED** [review]
LGTM

**Comment by symious** [comment]
@runzhiwang Thanks for the review.

**Review by elek — APPROVED** [review]
Thanks the fix @symious 

I tested this patch with starting Ozone.

After the first successful OM startup, I stopped a cluster and created a `raft-meta.tmp` manually. Earlier OM couldn't be started again, now it works well.

**Comment by symious** [comment]
@elek Thanks for the review and test.

**Comment by runzhiwang** [comment]
@symious Thanks the patch. @elek Thanks for review. I have merged the patch.

**Pull request merged**
