### PR TITLE
RATIS-1675. Revert  RATIS-1601 & RATIS-1391

### PR DESCRIPTION
**Pull request by codings-dan**
see https://issues.apache.org/jira/browse/RATIS-1675

### CODE REVIEW

**Comment by codings-dan** [comment]
@szetszwo Could you help take a look at this pull request? Thanks!

**Review by szetszwo — COMMENTED** [review]
+1 the change looks good.

@codings-dan , could you resolve the conflicts in TestSegmentedRaftLog.java?

**Comment by codings-dan** [comment]
@szetszwo I have resolved the conflicts, please take a look again, thanks!

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by codings-dan** [comment]
@szetszwo Thanks for helping review the pull request!

**Pull request merged**
