### PR TITLE
RATIS-1403. should not change state when request is rejected

### PR DESCRIPTION
**Pull request by JacksonYao287**
## What changes were proposed in this pull request?

it is found that , a leader receive a vote request and reject it , but it changes its state after the rejection. 
when  a leader/follower receives a vote request, if the request is reject , the leader/follower should not change its state, because that is an invalid request.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1403

## How was this patch tested?

current UT

### CODE REVIEW

**Comment by JacksonYao287** [comment]
@szetszwo PTAL!

**Comment by szetszwo** [comment]
According to the RAFT algorithm, the leader should step down when it sees a higher term. In requestVote(..), the leader recognizes a candidate only if the candidate has a higher term. Therefore, the leader should change to follower even if it will reject the vote from the candidate.

**Comment by JacksonYao287** [comment]
@szetszwo thanks for the review!
>In requestVote(..), the leader recognizes a candidate only if the candidate has a higher term. Therefore, the leader should change to follower even if it will reject the vote from the candidate.
yes , so , we can say that when the leader rejects a vote, it means the candidate must have a term lower or equal than the leader. if a candidate has a higher term, the leader should vote for it and step down to follower. 

so my point is that , before `changeToFollower` , we should check whether vote is granted.
if vote is granted , it means the candidate has a higher term , so it make sense to `changeToFollower`
if vote is not granted, it means the candidate has a equal or lower term,  `changeToFollower` should not be called.
so there does not exist any case that the leader reject the vote and meanwhile `changeToFollower`.

pleaser see the attached log below which i have uploaded in this jira.
```
2021-09-15 18:21:07,529 [grpc-default-executor-617] INFO org.apache.ratis.server.impl.VoteContext: a075f477-2523-4b79-991f-ecbe8ee00d0d@group-8BCFDCD73BCA-LEADER: reject ELECTION from b7bb63db-f11b-49c0-8269-2acf98d5fdd6: our last entry (t:3, i:432782) > candidate's last entry (t:3, i:302053)
2021-09-15 18:21:07,529 [grpc-default-executor-617] INFO org.apache.ratis.server.RaftServer$Division: a075f477-2523-4b79-991f-ecbe8ee00d0d@group-8BCFDCD73BCA: change Leader from a075f477-2523-4b79-991f-ecbe8ee00d0d to null at term 4 for updateCurrentTerm
2021-09-15 18:21:07,529 [grpc-default-executor-617] INFO org.apache.ratis.server.RaftServer$Division: a075f477-2523-4b79-991f-ecbe8ee00d0d@group-8BCFDCD73BCA: changes role from    LEADER to FOLLOWER at term 4 for candidate:b7bb63db-f11b-49c0-8269-2acf98d5fdd6
```
it show that the leader reject the vote because the candidate has a less up-to-date log(same term, but smaller index). after    this rejection, the leader does check whether the candidate has a higher term(voteGranted), and just go ahead to call `changeToFollower`,in which `state.updateCurrentTerm` is called.

**Comment by szetszwo** [comment]
> ... if vote is not granted, it means the candidate has a equal or lower term ...

This is not true.  The candidate can still have a higher term.

**Comment by szetszwo** [comment]
For the leader case, recognizeCandidate(candidateTerm) != null means the candidateTerm is higher.  However, decideVote(..) can still return false.

**Comment by JacksonYao287** [comment]
@szetszwo 
> For the leader case, recognizeCandidate(candidateTerm) != null means the candidateTerm is higher. 

yea , it is

>However, decideVote(..) can still return false.

 can you give a case that a candidate has a higher term(recognizeCandidate(candidateTerm) != null), but decideVote(..) still returns false? i think if candidate has a higher term, `ServerState.compareLog(lastEntry, candidateLastEntry)` will definitely return -1, so that decideVote(..) will return true!

please correct me if I miss something!

**Comment by kaijchen** [comment]
> can you give a case that a candidate has a higher term(recognizeCandidate(candidateTerm) != null), but decideVote(..) still returns false?

1. candidate's term >  leader's term
2. candidate's last log term < leader's last log term

Leader should reject the VoteFor request, and step down.

We can see the etcd's implementation for reference. Note in go, the switch-case doesn't fallthrough.
https://github.com/etcd-io/etcd/blob/706f256a054b2158ba5dc2e59cbab45826063829/raft/raft.go#L847

**Comment by kaijchen** [comment]
To avoid unnecessary step down, PreVote should be used.

**Comment by kaijchen** [comment]
For a detailed example, in 3-node Raft group.

| Node | Role | Term | Log Entries (Term-Index) |
| --- | --- | --- | --- |
| A | Leader | 1 | 1-1, 1-2, 1-3, 1-4, 1-5 |
| B | Candidate | 2 | 1-1, 1-2, 1-3 |
| C | Follower | 1 | 1-1, 1-2 |

1. B passed the PreVote stage, and became a candidate, `B {term = 2, voteFor = B}`.
2. B -> A: RequestForVote
    * **A rejects the vote request and steps down**, `A {term = 2, voteFor = None}`.
3. B -> C: RequestForVote
    * C accepts the vote request, `C {term = 2, voteFor = B}`.
4. B got quorum votes and became the new leader.
5. B begin to send AppendEntries requests to A and C.

The end result might look like this.

| Node | Role | Term | Log Entries (Term-Index) |
| --- | --- | --- | --- |
| A | Follower | 2 | 1-1, 1-2, 1-3, 2-1 |
| B | Leader | 2 | 1-1, 1-2, 1-3, 2-1, 2-2, 2-3 |
| C | Follower | 2 | 1-1, 1-2, 1-3, 2-1, 2-2 |

**Comment by JacksonYao287** [comment]
thanks @kaijchen for the review!

> To avoid unnecessary step down, PreVote should be used.

PreVote is very import and has been supported by RATIS, but for some uncertain reason , we disable it in some components of ozone(for example, scm)

```
RatisUtil.java
 /**
   * Set properties related to Raft leader election.
   *
   * @param properties RaftProperties instance which will be updated
   *
   */
  private static void setRaftLeadElectionProperties(
      final RaftProperties properties) {
    // Disable the pre vote feature (related to leader election) in Ratis
    RaftServerConfigKeys.LeaderElection.setPreVote(properties, false);
  }
```


> > i think if candidate has a higher term, `ServerState.compareLog(lastEntry, candidateLastEntry)` will definitely return -1, so that decideVote(..) will return true!
> 
> This is not true. The candidate has a higher term doesn't mean it has higher lastEntryTerm.
> 

the below is extracted from raft paper(5.4.1 Election restriction)

Raft uses the voting process to prevent a candidate from winning an election unless its log contains all committed entries. A candidate must contact a majority of the cluster in order to be elected, which means that every committed entry must be present in at least one of those servers. If the candidate’s log is at least as up-to-date as any other log in that majority (where “up-to-date” is defined precisely below), then it will hold all the committed entries. The RequestVote RPC implements this restriction: the RPC includes information about the candidate’s log, and the voter denies its vote if its own log is more up-to-date than that of the candidate.

Raft determines which of two logs is more up-to-date by comparing the index and term of the last entries in the logs. If the logs have last entries with different terms, then the log with the later term is more up-to-date. If the logs end with the same term, then whichever log is longer is more up-to-date.

so, here, the key point is what `up-to-date` stands for? according to the paper, a log with a higher term in its last entry is more up-to-date than a log with a lower term in its last entry. it means even if a log has a smaller index, it can also be more up-to-date than a log with a bigger index. that means a log with a shorter length can be much more up-to-date than a log with a longer length.   {index = 1, term = 100} is more up-to-date than {index = 100, term = 1}.

**Comment by kaijchen** [comment]
> it means even if a log has a smaller index, it can also be more up-to-date than a log with a bigger index. that means a log with a shorter length can be much more up-to-date than a log with a longer length. {index = 1, term = 100} is more up-to-date than {index = 100, term = 1}.

Yes, you are correct.

The point is, have higher term doesn't necessarily mean have higher lastLogTerm.

Candidate cannot append it's own log entry. Only leader can do that.

**Comment by kaijchen** [comment]
> 2\. candidate's last log (term, index) < leader's last log (term, index)

For clarification, I wrote this in Python's tuple comparism. 

`(a, b) < (x, y)` means `a < x || (a == x && b < y)`, which is equal to `less up-to-date than` in Raft.

**Comment by kaijchen** [comment]
For example,

If a candidate has `{term = 10, lastLogTerm = 5, lastLogIndex = 50}`,
and a leader has `{term = 5, lastLogTerm = 5, lastLogIndex = 100}`,
The leader should **reject the vote request and step down**.

**Comment by JacksonYao287** [comment]
> For example,
> 
> If a candidate has `{term = 10, lastLogTerm = 5, lastLogIndex = 50}`,
> and a leader has `{term = 5, lastLogTerm = 5, lastLogIndex = 100}`,
> The leader should **reject the vote request and step down**.

yea，according to raft paper,  a leader should step down and become follower if it discovers any server with a higher term.

but, i am not quite clear that is it necessary if the discovered server has a less up-to-date last logEntry? or will there be any problem if the leader does not step down to follower when it finds the raft peer , with a higher term, has a less up-to-date last logEntry?

 i would like to hear your views. @szetszwo @kaijchen

**Comment by szetszwo** [comment]
> ... will there be any problem if the leader does not step down ...

Yes, there is a problem -- that particular follower won't be able to join back.

**Comment by JacksonYao287** [comment]
> that particular follower won't be able to join back

good explanation!  thanks @szetszwo , it is clear to me now, i will close this PR

**Pull request closed without merging**
