### PR TITLE
RATIS-1838. Compare commit index with last included index when installSnapshot

### PR DESCRIPTION
**Pull request by SzyWilliam**
## What changes were proposed in this pull request?

See https://issues.apache.org/jira/browse/RATIS-1838

## How was this patch tested?

Existing unit tests and manual tests

### CODE REVIEW

**Comment by SzyWilliam** [comment]
Since the 2.5.1 release is incoming, I think we can include this simple PR in 2.5.1 for now. The ALREADY_INSTALLED solution and other more sophisticated tests can be performed later.

**Review by OneSizeFitsQuorum — APPROVED** [review]
LGTM~
For Raft, in extreme cases it is possible for lastIndex to be greater than lastSnapshotIndex, so this assertion is not reasonable

**Comment by OneSizeFitsQuorum** [comment]
@szetszwo cc

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Pull request merged**
