### PR TITLE
RATIS-1330. fix ratis-examples SubCommand parsePeers method ArrayIndexOutOfBounds exception

### PR DESCRIPTION
**Pull request by liutaohua**
Hi, I am a ratis novice and found an array out of bounds issue during testing

I added a check on the data where I manipulated array subscripts and threw an expected exception and hint

### CODE REVIEW

**Review by szetszwo — APPROVED** [review]
@liutaohua , thanks a lot for working on this.

+1 the change looks good.

**Comment by szetszwo** [comment]
The failed tests do not seem related.  Will merge this soon.

**Comment by szetszwo** [comment]
@liutaohua , I was about to merge this but a JIRA was not found for this pull request.  Could you file a JIRA at https://issues.apache.org/jira/projects/RATIS/ ?  We need a JIRA for merging this pull request.  Thanks.

**Comment by liutaohua** [comment]
> @liutaohua , I was about to merge this but a JIRA was not found for this pull request. Could you file a JIRA at https://issues.apache.org/jira/projects/RATIS/ ? We need a JIRA for merging this pull request. Thanks.

I've created Jira, but I'm at the airport. it's not convenient to add a more detailed description, sorry.

**Comment by szetszwo** [comment]
No problem.  It is good enough.  Thanks.  Have a nice trip.

**Pull request merged**
