### PR TITLE
RATIS-2173. Fix zero-copy bugs for non-gRPC cases.

### PR DESCRIPTION
**Pull request by szetszwo**
RATIS-2173

This is to fix the following bugs discovered in https://github.com/apache/ratis/pull/1156

5. LogAppenderDefault.sendAppendEntriesWithRetries(..) calls release() incorrectly for exception.

.
12. MemoryRaftLog has similar problems as in SegmentedRaftLog.

### CODE REVIEW

**Review by 133tosakarin — APPROVED** [review]

**Comment by szetszwo** [comment]
After a few retries, this can pass everything (although there are still zero-copy bugs).
- https://github.com/apache/ratis/actions/runs/11378907332

Let's move `ReferenceCountedLeakDetector.enable(..)` back to `MiniRaftClusterWithGrpc` for now in order to easier passing the tests.
- Indeed, the non-gRPC leaks are not real leaks since there are no underlying buffers to release.  Just the reference counts are incorrect.
- One kind of bugs may be related to `CodeInjectionForTesting` -- some tests may inject some code but not cleaning them up correctly.

**Comment by szetszwo** [comment]
@adoroszlai , in https://github.com/apache/ratis/actions/runs/11389343669/job/31704203350?pr=1167 , there were no test failures but the build failed.  Do you know why?  I see it serval times.

**Comment by adoroszlai** [comment]
> there were no test failures but the build failed. Do you know why?

Can happen if the test does not complete:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17:01 min
[INFO] Finished at: 2024-10-17T23:08:41Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project ratis-test: There was a timeout or other error in the fork -> [Help 1]
```

https://github.com/apache/ratis/actions/runs/11389343669/job/31704203350?pr=1167#step:5:909

**Comment by szetszwo** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project ratis-test: There was a timeout or other error in the fork -> [Help 1]
```
I saw this error but somehow there were no test timeout errors.  Not sure why.

**Comment by szetszwo** [comment]
@adoroszlai , could you review this?  I will continue debugging zero-copy after this.

**Review by adoroszlai — APPROVED** [review]

**Comment by adoroszlai** [comment]
Thanks @szetszwo for the patch, @133tosakarin for the review.

**Comment by szetszwo** [comment]
@adoroszlai , thanks a lot for reviewing the merging this!

**Pull request merged**
