### PR TITLE
RATIS-1444. Add metric to streaming

### PR DESCRIPTION
**Pull request by guohao-rosicky**
## What changes were proposed in this pull request?

Add metric to streaming

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1444

### CODE REVIEW

**Comment by guohao-rosicky** [comment]
I'm going to add metric, is that ok? @szetszwo Please look at this PR for me.  thanks.

**Comment by guohao-rosicky** [comment]
I'm going to add metric, is that ok? @szetszwo Please look at this PR for me.  thanks.

**Comment by guohao-rosicky** [comment]
I test PROM effect on ozone Datanode:
image

**Review by szetszwo — CHANGES_REQUESTED** [review]
@guohao-rosicky , thanks a lot for working on this.  I have quite a few suggestions; see https://issues.apache.org/jira/secure/attachment/13040505/607_review.patch

**Comment by guohao-rosicky** [comment]
@szetszwo Thanks, review my pr.  I have apply your patch. 

I will improve more metric in another PR later, mostly about Netty.

**Review by szetszwo — APPROVED** [review]
+1

**Pull request merged**
