### PR TITLE
RATIS-2225. RaftClientRequest leak in RaftServerImpl.

### PR DESCRIPTION
**Pull request by szetszwo**
See RATIS-2225

```java
//RaftServerImpl.submitClientRequestAsync
    try {
      assertLifeCycleState(LifeCycle.States.RUNNING);
    } catch (ServerNotReadyException e) {
      final RaftClientReply reply = newExceptionReply(request, e);
      requestRef.release();
      return CompletableFuture.completedFuture(reply);
    }
```
In the code above,
- it may catch `ServerNotReadyException` when the server is shutting down.
- It calls `newExceptionReply` which may throw another exception.

Then, requestRef.release() is not called.

Also, when a unchecked exception is thrown, it won't be logged.

### CODE REVIEW

**Review by adoroszlai — APPROVED** [review]
Thanks @szetszwo for the fix, LGTM.

Currently [running](https://github.com/adoroszlai/ratis/actions/runs/12471796862) 10x10 test.

**Comment by szetszwo** [comment]
> Currently [running](https://github.com/adoroszlai/ratis/actions/runs/12471796862) 10x10 test.

I ran it earlier.  This change cannot completely fix the problem.  We also need RATIS-2184.  Then, it seems very close.
- master: Total failures 42 https://github.com/apache/ratis/actions/runs/12416764228/job/34669317055
- RATIS-2225 only: Total failures 27 https://github.com/szetszwo/ratis/actions/runs/12448409593/job/34753607305
- RATIS-2184 only: Total failures 20 https://github.com/szetszwo/ratis/actions/runs/12414246844/job/34661434032
- RATIS-2225 + RATIS-2184: Total failures 2 https://github.com/szetszwo/ratis/actions/runs/12448873327/job/34754409100

**Comment by szetszwo** [comment]
@adoroszlai , thanks a lot for reviewing and merging this!

**Comment by szetszwo** [comment]
Master after merged both RATIS-2225 and RATIS-2184: Total failures 3 https://github.com/apache/ratis/actions/runs/12472282367/job/34811870836

**Pull request merged**
