### PR TITLE
RATIS-1821. Upgrade ratis-thirdparty version to 1.0.4

### PR DESCRIPTION
**Pull request by SzyWilliam**
see https://issues.apache.org/jira/browse/RATIS-1821

### CODE REVIEW

**Review by adoroszlai — APPROVED** [review]
Thanks @SzyWilliam for the patch.

@szetszwo is also making the same change as part of RATIS-1820, but I think making it separately from other version bumps is cleaner.

**Review by szetszwo — APPROVED** [review]
Let's bump the third party version here.

+1 the change looks good.

**Comment by szetszwo** [comment]
@SzyWilliam, thanks a lot for working on this!

@adoroszlai , thanks a lot for reviewing this!

**Comment by SzyWilliam** [comment]
Thanks @adoroszlai and @szetszwo for reviewing!

**Pull request merged**
