### PR TITLE
RATIS-1804. Change the default number of outstanding append entries.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1804

### CODE REVIEW

**Comment by szetszwo** [comment]
Also fix `STATISTICS_EXPIRY_TIME_DEFAULT`: MICROSECONDS should be MILLISECONDS.

**Review by OneSizeFitsQuorum — APPROVED** [review]
LGTM~
BTW, perhaps we can introduce follower sync status, like etcd's [solution](https://github.com/etcd-io/etcd/blob/7e4fc7eaa931298732c880a703bccc9c177ae1de/raft/progress.go#L39-L50), to reduce the number of pipieline when the leader switches or snapshot transfers and increase the number of pipelines during normal operation. This may lead to better performance overall

**Review by SzyWilliam — APPROVED** [review]
+1 the changes look good to me.

**Comment by szetszwo** [comment]
@SzyWilliam , thanks for reviewing this!

**Pull request merged**
