### PR TITLE
RATIS-1608. Improve RaftStorageDirectoryImpl#tryLock performance on ios system

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/RATIS-1608

### CODE REVIEW

**Comment by ChenSammi** [comment]
cc @szetszwo .  The failed UT looks irrelevant.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by ChenSammi** [comment]
Thanks @szetszwo , could you help to merge it?

**Comment by ChenSammi** [comment]
Thanks @szetszwo .

**Pull request merged**
