### PR TITLE
Update downloads.html for RATIS-1394 and RATIS-1395

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Changes in the generated Ratis website for RATIS-1394 and RATIS-1395.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1394
https://issues.apache.org/jira/browse/RATIS-1395

## How was this patch tested?

 * `open downloads.html`
 * verify changes from those two issues are applied

### CODE REVIEW

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by adoroszlai** [comment]
Thanks @szetszwo for the review.

**Comment by adoroszlai** [comment]
@szetszwo [Ratis website](https://ratis.apache.org/downloads.html) still shows old content.  Are there any other steps that need to be done for it to be updated?

**Comment by szetszwo** [comment]
I don't recall any additional steps.  Let me check ...

**Comment by szetszwo** [comment]
According to https://infra.apache.org/project-site.html , we should have (but we current do not have) the following in .asf.yaml
```
publish:
  whoami:  asf-site
```

**Pull request merged**
