### PR TITLE
RATIS-1683. Upgrade ubuntu version from 18.04 to 20.04

### PR DESCRIPTION
**Pull request by codings-dan**
see https://issues.apache.org/jira/browse/RATIS-1683

### CODE REVIEW

**Comment by codings-dan** [comment]
@adoroszlai Could you help take a look at this pull request? Thanks!

**Comment by codings-dan** [comment]
@adoroszlai hi, it seems that new ci can't be triggered now, do you know what's going on?

**Comment by adoroszlai** [comment]
> it seems that new ci can't be triggered now, do you know what's going on?

Yes, indentation for the new setup-java step does not match the existing one.  Sorry about that.

[Invalid workflow file: .github/workflows/post-commit.yml#L176](https://github.com/apache/ratis/actions/runs/2904516017/workflow)
You have an error in your yaml syntax on line 176

**Review by adoroszlai — APPROVED** [review]
Thanks @codings-dan for the patch.

**Comment by codings-dan** [comment]
@adoroszlai Thanks a lot for helping review and merge the pull request!

**Pull request merged**
