### PR TITLE
RATIS-1799. Make shell scripts in binary package executable

### PR DESCRIPTION
**Pull request by kaijchen**
https://issues.apache.org/jira/browse/RATIS-1799

### CODE REVIEW

**Comment by kaijchen** [comment]
Cc @szetszwo @codings-dan PTAL.

**Comment by kaijchen** [comment]
Hi @adoroszlai, I think it's nice to have this PR included in the next release (2.4.2 or 2.5.0).

**Review by adoroszlai — APPROVED** [review]
Thanks @kaijchen for the patch, LGTM.

Before:

```
-rw-r--r-- root/root      2152 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/bin/ratis
-rw-r--r-- root/root      1150 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/examples/bin/client.sh
-rw-r--r-- root/root      1871 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/examples/bin/common.sh
-rw-r--r-- root/root       933 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/examples/bin/server.sh
-rw-r--r-- root/root      1610 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/examples/bin/start-all.sh
-rw-r--r-- root/root       922 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/examples/bin/stop-all.sh
-rw-r--r-- root/root      3626 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/libexec/ratis-shell-config.sh
```

After:

```
-rwxr-xr-x root/root      2152 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/bin/ratis
-rwxr-xr-x root/root      1150 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/examples/bin/client.sh
-rwxr-xr-x root/root      1871 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/examples/bin/common.sh
-rwxr-xr-x root/root       933 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/examples/bin/server.sh
-rwxr-xr-x root/root      1610 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/examples/bin/start-all.sh
-rwxr-xr-x root/root       922 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/examples/bin/stop-all.sh
-rwxr-xr-x root/root      3626 2020-01-22 16:10 apache-ratis-3.0.0-SNAPSHOT-bin/libexec/ratis-shell-config.sh
```

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.  Thanks for fixing this mysterious problem!

**Comment by szetszwo** [comment]
@adoroszlai , thanks a lot for reviewing and testing this!

**Pull request merged**
