### PR TITLE
RATIS-1657. Intermittent failure in TestLogAppenderWithGrpc#testPendingLimits due to ConcurrentModificationException at SlidingWindow$Client.trySendDelayed.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1657

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
Thanks @szetszwo for working on this.  Unfortunately the exception is still reproducible, happened in 2/100 runs.

https://github.com/adoroszlai/incubator-ratis/runs/7667867516?check_suite_focus=true#step:5:4904
https://github.com/adoroszlai/incubator-ratis/runs/7667867808?check_suite_focus=true#step:5:8734

Is it possible that the send method invoked from within `acceptAllAndClear`'s loop results in a call to put/remove any other item?  In other words, may it be a modification in the same thread?  I would think modification by other threads is prevented by the synchronization in the patch.

And an assertion failed in 1/100 runs:
https://github.com/adoroszlai/incubator-ratis/runs/7667867709?check_suite_focus=true#step:5:7368

**Comment by szetszwo** [comment]
@adoroszlai , thanks a lot for testing this.  Then, we have to copy the seqNums before calling `sendMethod.accept(..)`

**Review by adoroszlai — APPROVED** [review]
Thanks @szetszwo for updating the patch, now the test passed 200/200.

**Comment by szetszwo** [comment]
@adoroszlai , thanks a lot for testing and reviewing this!

**Pull request merged**
