### PR TITLE
RATIS-2160. MetricRegistriesLoader should not print INFO message in CLI.

### PR DESCRIPTION
**Pull request by szetszwo**
See RATIS-2160

### CODE REVIEW

**Review by OneSizeFitsQuorum — APPROVED** [review]
LGTM

**Comment by szetszwo** [comment]
Test this over 3.1.1 with #1158

**Comment by szetszwo** [comment]
This passed all the tests in https://github.com/apache/ratis/pull/1158 over release-3.1.1.  The failures here are unrelated.

**Comment by szetszwo** [comment]
The failure is tracked by RATIS-2151.

**Comment by szetszwo** [comment]
@OneSizeFitsQuorum , thanks a lot for reviewing this!

**Pull request merged**
