### PR TITLE
RATIS-1970. Add junit 5 dependencies.

### PR DESCRIPTION
**Pull request by nandakumar131**
## What changes were proposed in this pull request?

Junit 5 dependencies are added to the appropriate pom files.

## What is the link to the Apache JIRA

RATIS-1970

## How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
Thanks @nandakumar131 for the patch, LGTM.

**Comment by szetszwo** [comment]
@nandakumar131 , thanks a lot for working on JUnit5 migration!  For the dependencies, let's add them when they are needed (i.e. add them with the tests).  We minimize the dependencies because Ratis is a library.  We should make it easier to be consumed.

For JUnit5 migration, we may start with ratis-common since it only has a few tests.  It can show how the migration works.

**Comment by nandakumar131** [comment]
Thanks for the review @adoroszlai &  @szetszwo.

@szetszwo, sure. will do.

FYI: The scope of the junit dependencies are of scope `test`, so it will not be part of Ratis's transitive dependencies.

**Comment by nandakumar131** [comment]
@szetszwo, I have been working on limiting the changes just to `ratis-common`, but the test compilation started failing on `ratis-server`, `ratis-test` & `ratis-examples` as they extend `BaseTest` from `ratis-common`.

I will try to limit the changes on each PR to make the review process easier.

This PR will only update the parent `pom.xml` and `ratis-common`'s `pom.xml`

Test-case changes will happen in follow-up PRs.

**Comment by szetszwo** [comment]
> FYI: The scope of the junit dependencies are of scope test, so it will not be part of Ratis's transitive dependencies.

@nandakumar131 , I understand that the test dependencies are not transitive.  That's a good point!

It is usually hard to remove dependencies.  So I really oppose adding unused dependencies.  Moreover, we have to handle it in case of CVEs.

Please include some change to use the dependencies in this pull requests.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Pull request merged**
