### PR TITLE
RATIS-1879. Handle RaftLog corruption when unsafe flush is enabled.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1879

### CODE REVIEW

**Comment by SzyWilliam** [comment]
Thanks @szetszwo very much for the patch! I'll use the patch to restart and see if we can fix it later on.

**Comment by szetszwo** [comment]
@SzyWilliam , as @OneSizeFitsQuorum mentioned in [RATIS-1879](https://issues.apache.org/jira/browse/RATIS-1879).  We already have WARN_AND_RETURN corruption policy.  We does not seem to need this anymore.

**Comment by SzyWilliam** [comment]
@szetszwo Thanks a lot! I was still worrying about this issue yesterday since it turned out that our user turned off the `unsafeFlush` and I made a mistake when firing a issue. The corruption problem may happen whether we enable `unsafeFlush`  or not. 
Now that I know `CorruptionPolicy` and it perfectly meet our needs. 
Thanks @szetszwo @OneSizeFitsQuorum again!

**Comment by OneSizeFitsQuorum** [comment]
@szetszwo it looks like you already addressed the issue reported by Ozone four years ago, which is really cool. Thank you for your thorough work!!!

**Comment by szetszwo** [comment]
Closing this since the problem is already fixed.

**Pull request closed without merging**
