### PR TITLE
RATIS-1923. Netty: atomic operations require side-effect-free functions.

### PR DESCRIPTION
**Pull request by szetszwo**
See RATIS-1923

### CODE REVIEW

**Comment by guohao-rosicky** [comment]
Thanks @szetszwo work on this,  LGTM

`The update methods in AtomicReference run in a loop and may call the update function multiple time. The old values created by the update function may be discarded without cleaning up` 

Yes, this issue does occur when reconnecting multiple times quickly.

**Comment by szetszwo** [comment]
@guohao-rosicky , thanks a lot for reviewing and merging this!

**Comment by guohao-rosicky** [comment]
Hi @szetszwo .

I used this patch on my Ozone production environment.
Observed that s3 gateway and datanode would have an excessive number of open files.
It's caused by too many connections on port 9855, and I suspect that this patch causes the inability to close handles.

`
# lsof -p 407922 (datanode)
[root@ozone01 tmp]# grep 9855 407922-datanode.lsof | wc -l
152375
[root@ozone01 tmp]# wc -l 407922-datanode.lsof 
156215 407922-datanode.lsof

# lsof -p 265960 (s3 gateway)
[root@ozone01 tmp]# grep 9855 265960-s3gateway.lsof | wc -l
159474
[root@ozone01 tmp]# wc -l 265960-s3gateway.lsof
164088 265960-s3gateway.lsof
`

**Comment by szetszwo** [comment]
@guohao-rosicky , thanks for testing this!  Do you have RATIS-1948?

**Comment by guohao-rosicky** [comment]
Didn't include [RATIS-1948](https://issues.apache.org/jira/browse/RATIS-1948), I'll add it and try it, thanks @szetszwo  for the help.

**Pull request merged**
