### PR TITLE
RATIS-1935. Remove yetus related code.

### PR DESCRIPTION
**Pull request by szetszwo**
See RATIS-1935

### CODE REVIEW

**Review by SzyWilliam — APPROVED** [review]
+1 the changes look good to me. 
Also I find YETUS in `nightly-build.sh`, `precommit-build.sh`, `common.sh`, not sure if they are related.

**Comment by szetszwo** [comment]
@SzyWilliam , you are right.  These files should also be removed.

@adoroszlai , could you also review this?

**Review by adoroszlai — COMMENTED** [review]
Thanks @szetszwo for working on this.

I found two more references:

1. `dev-support/test-patch` uses `yetus-wrapper` and `yetus-personality.sh`, which are being removed.  I think `test-patch` should be removed, too.

https://github.com/apache/ratis/blob/c8d74d056bcbe2ae1dd042bb1e70d044a45cfa00/dev-support/test-patch#L17-L18

2. A "hack" in `ratis-proto/pom.xml`.  I think we can try to remove it.  If removal causes any build issue, we can also keep it.

https://github.com/apache/ratis/blob/c8d74d056bcbe2ae1dd042bb1e70d044a45cfa00/ratis-proto/pom.xml#L105-L119

**Comment by szetszwo** [comment]
@adoroszlai , thanks a lot for the suggestions!  Pushed a commit addressing them.

**Review by adoroszlai — APPROVED** [review]
Thanks @szetszwo for updating the patch.

**Comment by adoroszlai** [comment]
Thanks @szetszwo for the patch, @SzyWilliam for the review.

**Pull request merged**
