### PR TITLE
RATIS-2057. Add back JavaUtils.attemptUntilTrue(..).

### PR DESCRIPTION
**Pull request by szetszwo**
See  RATIS-2057

### CODE REVIEW

**Comment by adoroszlai** [comment]
Thanks @szetszwo for the patch.

**Comment by szetszwo** [comment]
> ... does that mean applications should not use "JavaUtils" in the future  ... ?

That's is a good question!  For now, we may consider the APIs in classes like `JavaUtils` are `experimental` (similar to [Java 9 jfr](https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/jdk/jfr/Experimental.html) or [grpc](https://grpc.github.io/grpc-java/javadoc/io/grpc/ExperimentalApi.html)).   We will make the APIs more stable when we establish the public ratis -common-api.

**Comment by szetszwo** [comment]
@adoroszlai , thanks a lot for reviewing and merging this!

**Comment by symious** [comment]
> For now, we may consider the APIs in classes like JavaUtils are experimental (similar to [Java 9 jfr](https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/jdk/jfr/Experimental.html) or [grpc](https://grpc.github.io/grpc-java/javadoc/io/grpc/ExperimentalApi.html)). We will make the APIs more stable when we establish the public ratis -common-api.

@szetszwo Thank you for the explaination.

**Pull request merged**
