### PR TITLE
RATIS-2016. Correct NotificationInstallSnapshot's index

### PR DESCRIPTION
**Pull request by symious**
## What changes were proposed in this pull request?

Currently the index of notify installSnapshot is decided by "
request.getSnapshotChunk().getRequestIndex()", which is valid because the proto is 0, this should be specified implicit to avoid confusion.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-2016

## How was this patch tested?

Original tests in `InstallSnapshotNotificationTests` should be fine.

### CODE REVIEW

**Review by szetszwo — COMMENTED** [review]
@symious , thanks for filing this bug!  Please see the comments inlined and also https://issues.apache.org/jira/secure/attachment/13066289/1030_review.patch

**Comment by symious** [comment]
@szetszwo Updated, PTAL.

**Comment by szetszwo** [comment]
@symious , why having 54cd580b17bc9741cc2cd71c0ab8fd66553eacc3 ?  The check seems correct.

**Comment by symious** [comment]
> why having https://github.com/apache/ratis/commit/54cd580b17bc9741cc2cd71c0ab8fd66553eacc3 ? The check seems correct.

@szetszwo The leader can send multiple requests before receiving the reply, so when received the first request with index 0, the queue will not be empty.

**Comment by szetszwo** [comment]
@symious , you are right.  It is a queue but not a stack!

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by symious** [comment]
@szetszwo Thank your for the review and merge.

**Pull request merged**
