### PR TITLE
RATIS-2081. Comment that we skip checkstyle on test directory on purpose

### PR DESCRIPTION
**Pull request by symious**
## What changes were proposed in this pull request?

Checkstyle is not checking test source directory. This ticket is to resolve this issue.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-2081

## How was this patch tested?

No need new tests.

### CODE REVIEW

**Comment by symious** [comment]
@szetszwo Updated the comment, PTAL.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Comment by szetszwo** [comment]
@symious , could you also update the title?

**Comment by symious** [comment]
@szetszwo Updated, thanks for the review.

**Pull request merged**
