### PR TITLE
RATIS-1873. Fix retry cache warning condition

### PR DESCRIPTION
**Pull request by SzyWilliam**
Made a mistake in previous PR https://github.com/apache/ratis/pull/904. The conditions here are a bit of tricky.

The cache entry is expected to be **not completed normally** when `replyPendingRequest`, since we'll complete this cache entry at the very end of `replyPendingRequest`.

The explanation why this assertion fails in previous PR is incorrect. The real path leading to the error is:
If the request r arrived, committed, but became timeout due to blocking apply (may be stuck in a synchronous snapshotting), a client may choose to retry r. However, if the retry gap exceeds retryCache expiration duration (in our case, yes), the very same request r would be committed, **again**. After the snapshotting finished, these two identical requests being applied would cause the assertion to fail.

Maybe we should recommend users to set a retry cache expiration duration longer than the client retry-waiting duration?

### CODE REVIEW

**Comment by szetszwo** [comment]
> Maybe we should recommend users to set a retry cache expiration duration longer than the client retry-waiting duration?

Yes, it is a must.  RetryCache is to tolerate client retries.  The cache expiration must be longer than the client retry.

**Review by szetszwo — APPROVED** [review]
You are right!  The original assertion is to make sure the cache is not completed.  We should negate it for the warning.

+1 the change looks good.

**Comment by SzyWilliam** [comment]
This change also happens to address another long-standing issue that had been bothering me. We occasionally encountered the 'apply twice' problem, and I had previously believed that the only solution was to add a retry cache to the state machine to definitively eliminate this possibility. However, it turns out that we can resolve the issue simply by setting a longer expiration timeout. Problem solved!

**Review by szetszwo — APPROVED** [review]
+1 the doc looks good.

**Comment by szetszwo** [comment]
@SzyWilliam , please file a new JIRA instead of reusing a previous JIRA.  It is easier to track.  :)

**Comment by SzyWilliam** [comment]
@szetszwo Thanks for merging this and the reminding! I will use a new jira next time.

**Review by OneSizeFitsQuorum — COMMENTED** [review]
Thanks @SzyWilliam for your careful consideration!

**Pull request merged**
