### PR TITLE
RATIS-2052. Add docs for triggering snapshot when removing raftGroup parameter.

### PR DESCRIPTION
**Pull request by OneSizeFitsQuorum**
see [jira](https://issues.apache.org/jira/browse/RATIS-2052)

### CODE REVIEW

**Comment by OneSizeFitsQuorum** [comment]
@szetszwo PTAL

**Review by szetszwo — COMMENTED** [review]
+1 the change looks good.

@OneSizeFitsQuorum , could you file a new JIRA?  Let's have a JIRA per commit.  It is easier to track.

**Comment by OneSizeFitsQuorum** [comment]
> @OneSizeFitsQuorum , could you file a new JIRA? Let's have a JIRA per commit. It is easier to track.
Thanks for reminding! Done!

**Review by szetszwo — APPROVED** [review]
+1

@OneSizeFitsQuorum , thanks for filing the JIRA.  BTW, you may simply use RATIS-2052, instead of [JIRA](https://issues.apache.org/jira/browse/RATIS-2052).  We have setup that RATIS-XXXX will be automatically converted to a link.

**Comment by OneSizeFitsQuorum** [comment]
> +1
> 
> @OneSizeFitsQuorum , thanks for filing the JIRA. BTW, you may simply use [RATIS-2052](https://issues.apache.org/jira/browse/RATIS-2052), instead of [JIRA](https://issues.apache.org/jira/browse/RATIS-2052). We have setup that [RATIS-XXXX](https://issues.apache.org/jira/browse/RATIS-XXXX) will be automatically converted to a link.

Sorry I made a mistake, I will pay attention to it later ~

**Pull request merged**
