### PR TITLE
RATIS-1147. TestMultiRaftGroup on MiniRaftClusterWithNetty is failing…

### PR DESCRIPTION
**Pull request by cnauroth**
… consistently

## What changes were proposed in this pull request?

Change tests to bind server sockets to loopback interface instead of wildcard.  This resolves intermittent bind failures from unclosed sockets during some tests like `TestMultiRaftGroup`.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1147

## How was this patch tested?

`TestMultiRaftGroup` consistently failed on Mac before this patch.  After this patch, it consistently passes, and I have all Ratis tests passing on Mac.  I also ran `TestMultiRaftGroup` in the Ubuntu image to confirm no harm done to Linux.

### CODE REVIEW

**Review by szetszwo — COMMENTED** [review]
@cnauroth , thanks a lot for working on this!

NetUtils.createLocalServerAddress() is used by org.apache.ratis.logservice.server.BaseServer which is not in test (it is under src/main). Not sure if this would break it.

**Comment by cnauroth** [comment]
@szetszwo , thank you for reviewing!

I hadn't caught the usage in `BaseServer`, so thank you for telling me.  I've pushed up another commit on my branch that I think shows the change is safe there.  For runs of `TestMetaServer`, I've changed allocation of workers in `LogServiceCluster` so that it will not set a port explicitly, and therefore the test hits the previously uncovered code in `BaseServer.Builder#validate()`.  For the masters, I couldn't do the same thing, because we need to know the full set of addresses up front to configure for quorum.  However, I was able to change it to use `NetUtils#createLocalServerAddress(int)`, so it's a different way of proving the change is safe.

This is probably a good change for the ratis-logservice tests.  Previously, `LogServiceCluster` required free ports in the 9xxx and 10xxx range, which might not be guaranteed on every machine.  Now the tests can pick any available ephemeral ports.

**Review by szetszwo — APPROVED** [review]
Thanks for checking the code and the update.

+1 the change looks good.

**Comment by szetszwo** [comment]
Reopen for restarting the build.

**Comment by cnauroth** [comment]
It seems like tests with the simulated RPC are failing pretty often, regardless of code changes under test.  I'm not yet familiar with all of these test suites.  It doesn't look related to this patch, but what do long-time committers think?  Are the simulated RPC tests just flaky?

**Comment by szetszwo** [comment]
I just have checked a few past builds.  TestRaftReconfigurationWithGrpc (failed) and TestNettyDataStreamChainTopologyWithGrpcCluster (timeout 100 seconds) did fail often.

The simulated RPC tests look okay.

**Comment by szetszwo** [comment]
@cnauroth , you are right that the failed tests do not seem related.  I just have merged this.  Thanks a lot for your contribution!

**Pull request merged**
