### PR TITLE
Integrate ratis-shell

### PR DESCRIPTION
**Pull request by maobaolong**
## What changes were proposed in this pull request?

Add ratis-shell as a module of ratis

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1412

## How was this patch tested?

```bash
mvn clean install  assembly:single -DskipTests -Dmaven.javadoc.skip=true -Dlicense.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Denforcer.skip=true   -Djsse.enableSNIExtension=false  -Prelease -Papache-release

cd ratis-assembly/target
tar -xzvf apache-ratis-2.2.0-SNAPSHOT-ratis-shell.tar.gz
cd apache-ratis-2.2.0-SNAPSHOT
# Get ozone manager ratis information
bin/ratis sh info -peers ratis.shell.ozone-om.peers=localhost:9872,localhost:19872,localhost:29872
# Elect localhost:29872 to be new leader of ozone manager
bin/ratis sh elect -peers ratis.shell.ozone-om.peers=localhost:9872,localhost:19872,localhost:29872 -address localhost:29872 
```

### CODE REVIEW

**Comment by maobaolong** [comment]
@szetszwo Thanks for your discussion with me in the jira, now I push the ratis-shell as a module, please take a look.

**Comment by maobaolong** [comment]
ping @szetszwo

**Comment by maobaolong** [comment]
@szetszwo As we cut this PR into sub tasks, I close this PR now. Thank you.

**Comment by szetszwo** [comment]
@maobaolong , thanks a lot for breaking this into subtasks.

**Pull request closed without merging**
