### PR TITLE
RATIS-1900. Do not use FileInputStream/FileOutputStream.

### PR DESCRIPTION
**Pull request by szetszwo**
See RATIS-1900

### CODE REVIEW

**Review by adoroszlai — COMMENTED** [review]
Thanks @szetszwo for the patch.  There is one more usage of `FileInputStream` left in:

https://github.com/apache/ratis/blob/aa99ff69d76a5fcee2e12ce2fdc7f7e4d75bf97e/ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogReader.java#L148

Is that intentional?

Also, it would be nice to use `maven-enforcer-plugin` to ban import of `FileInputStream`/`FileOutputStream` to avoid future patches reintroducing it.

**Comment by szetszwo** [comment]
@adoroszlai , thanks for reviewing this!  Updated `SegmentedRaftLogReader` and also added `bannedImports`.

**Review by adoroszlai — COMMENTED** [review]
Thanks @szetszwo for updating the patch.  LGTM, but being rather big change, I think it would be great to have multiple reviews.

**Comment by szetszwo** [comment]
@adoroszlai , I agree that this is not a simple change.  Let me separate this to two, three JIRAs.

**Review by adoroszlai — APPROVED** [review]

**Comment by szetszwo** [comment]
@adoroszlai , thanks a lot for reviewing this!

**Pull request merged**
