### PR TITLE
RATIS-1743. Memory leak in SegmentedRaftLogWorker due to metrics.

### PR DESCRIPTION
**Pull request by szetszwo**
See https://issues.apache.org/jira/browse/RATIS-1743

This is the third attempt.

### CODE REVIEW

**Comment by szetszwo** [comment]
@adoroszlai , just found that simply using `AtomicReference` for the `sharedBuffer` could fix the failure of `TestStorageContainerManagerHA`.

**Review by adoroszlai — APPROVED** [review]
Nice!

**Comment by szetszwo** [comment]
@adoroszlai , thanks a lot for reviewing and testing this!

**Comment by SzyWilliam** [comment]
@szetszwo Bravo! I've been following this issue, 
`metricRegistry` holds reference to `SegmentedRaftLogWorker` after close() due to lambda closure. `SegmentedRaftLogWorker` also holds the reference to the memorized supplier of shared buffer. Thus, the shared buffer cannot be automatically collected, we have to manually set it to null in `close()` hook, just as this PR did. Am I getting it right?

**Comment by SzyWilliam** [comment]
The original purpose to use MemorizedSupplier is to avoid passing shared buffer's array reference out of the `SegmentedRaftLogWorker`. It great to learn that `AtomicReference` would work.

**Comment by SzyWilliam** [comment]
Also, shall we export this patch to 2.4.1?

**Comment by szetszwo** [comment]
@SzyWilliam , it is included in 2.4.1 rc2.

@adoroszlai , could you check and vote for the rc2 when you have time?  Cc @codings-dan

**Pull request merged**
