### PR TITLE
RATIS-1325. Change 2020 to 2021 in NOTICE

### PR DESCRIPTION
**Pull request by runzhiwang**
## What changes were proposed in this pull request?

Change 2020 to 2021 in NOTICE

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/RATIS-1325

## How was this patch tested?

No need new ut

### CODE REVIEW

**Comment by runzhiwang** [comment]
@szetszwo Could you help review this ? Thanks a lot.

**Comment by szetszwo** [comment]
We should also update ratis-assembly/src/main/resources/NOTICE .

**Comment by runzhiwang** [comment]
@szetszwo Do we need to change 2020 in LICENSE file ?
image

**Comment by szetszwo** [comment]
> ...  Do we need to change 2020 in LICENSE file ?

I am not sure.  Let's me check.

**Comment by szetszwo** [comment]
According to https://github.com/apache/ratis/blob/master/ratis-docs/themes/ratisdoc/static/js/bootstrap.min.js , we are using
 Bootstrap v3.4.1 so that we should set the years to 2011-2019.

BTW, please also add v3.4.1.  Thanks.

**Comment by szetszwo** [comment]
@runzhiwang , as a summary, we should have the following changes:
{code}
+++ b/LICENSE
@@ -237,8 +237,8 @@ OF SUCH DAMAGE.
 
 --
 
-Bootstrap
----------
+Bootstrap v3.4.1
+----------------
 The product bundles Bootstrap in these paths:
 
 ratis-docs/themes/ratisdoc/static/css/bootstrap*
@@ -247,8 +247,8 @@ which is licensed under MIT
 
 The MIT License (MIT)
 
-Copyright (c) 2011-2020 Twitter, Inc.
-Copyright (c) 2011-2020 The Bootstrap Authors
+Copyright (c) 2011-2019 Twitter, Inc.
+Copyright (c) 2011-2019 The Bootstrap Authors
 
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
@@ -270,8 +270,8 @@ THE SOFTWARE.
 
 --
 
-JQuery
-------
+JQuery v3.4.1
+-------------
 The product bundles JQuery in
 ratis-docs/themes/ratisdoc/static/js/jquery-3.4.1.min.js
 which is licensed under MIT
{code}

**Comment by runzhiwang** [comment]
@szetszwo Thanks, have updated the patch.

**Review by szetszwo — APPROVED** [review]
+1 the change looks good.

**Pull request merged**
